
version: 2

# Khai báo sources cho dataset silver
sources:
  - name: silver
    description: "Dataset silver chứa các bảng đã được xử lý ở mức silver"
    tables:
      - name: combine
        description: "Bảng kết hợp dữ liệu giao dịch và sản phẩm"
      - name: cust_loc
        description: "Bảng thông tin khách hàng và vị trí địa lý"

  - name: test  # Dataset test chứa các bảng gốc
    description: "Dataset test chứa dữ liệu gốc"
    tables:
      - name: transaction
        description: "Bảng giao dịch gốc"
      - name: customer
        description: "Bảng thông tin khách hàng gốc"
      - name: product
        description: "Bảng thông tin sản phẩm gốc"
      - name: city
        description: "Bảng thông tin thành phố gốc"

# Khai báo models


        tests:
        data_tests:
        tests:
        data_tests:

